// Browser-facing diagnostic codes. Never reveal provider payloads, tokens or secrets.
const SAFE_CODES = new Set([
  'UPSTOX_REAUTHENTICATION_REQUIRED',
  'UPSTOX_ANALYTICS_TOKEN_INVALID_OR_EXPIRED',
  'UPSTOX_ANALYTICS_PERMISSION_DENIED',
  'UPSTOX_RATE_LIMITED',
  'UPSTOX_LIVE_QUOTE_FAILED',
  'UPSTOX_LIVE_QUOTE_EMPTY',
  'UPSTOX_LIVE_QUOTE_INSTRUMENT_MISMATCH',
  'UPSTOX_INTRADAY_REQUEST_FAILED',
  'UPSTOX_INTRADAY_DATA_EMPTY',
  'UPSTOX_DERIVATIVE_SEARCH_FAILED',
  'UPSTOX_INSTRUMENT_SEARCH_FAILED',
  'UPSTOX_EQUITY_NOT_FOUND',
  'UPSTOX_OPTION_GREEKS_UNAVAILABLE',
  'UPSTOX_HISTORICAL_DATA_REQUEST_FAILED',
  'UPSTOX_HISTORICAL_DATA_EMPTY',
  'UPSTOX_MARKET_DATA_UNAVAILABLE',
  'UPSTOX_MARKET_DATA_REQUEST_FAILED',
  'UPSTOX_FUNDAMENTALS_REQUEST_FAILED',
  'INVALID_INSTRUMENT_KEY',
  'INVALID_DERIVATIVE_SEARCH',
  'INVALID_INTRADAY_INTERVAL',
  'INVALID_INSTRUMENT_QUERY',
  'INVALID_DATE_RANGE'
]);
export function normalizeReadOnlyFailure(status,body={}){
  if(status===401)return body?.error==='UPSTOX_ANALYTICS_TOKEN_INVALID_OR_EXPIRED'?'UPSTOX_ANALYTICS_TOKEN_INVALID_OR_EXPIRED':'UPSTOX_REAUTHENTICATION_REQUIRED';
  if(status===429)return 'UPSTOX_RATE_LIMITED';
  if(status===404)return 'BACKEND_ROUTE_NOT_DEPLOYED';
  if(status===403)return body?.error==='UPSTOX_ANALYTICS_PERMISSION_DENIED'?'UPSTOX_ANALYTICS_PERMISSION_DENIED':'UPSTOX_PERMISSION_DENIED';
  const code=typeof body?.error==='string'?body.error:'';
  if(SAFE_CODES.has(code))return code;
  if(status===502||status===503||status===504)return 'UPSTOX_MARKET_DATA_UNAVAILABLE';
  if(status>=500)return 'UPSTOX_BACKEND_SERVER_ERROR';
  return 'UPSTOX_READ_ONLY_API_FAILED';
}
