import assert from 'node:assert/strict';
import {marketClockState,commodityGroup} from './services/intradayMarketClock.js';
import {classifyIntradayInstrument,INTRADAY_SAFETY} from './services/intradayInstrumentContract.js';
import {analyzeIntradayCandles} from './services/intradayTechnicalEngine.js';
import {assessIntradayInstrumentRisk,extractUpstoxLiveQuoteEvidence} from './services/intradayRiskEngine.js';
import {evaluateIntradayRecommendation} from './services/intradayRecommendationEngine.js';

const at=iso=>Date.parse(iso);
const oct='2026-10-08T';
const session=(symbol,time)=>marketClockState({segment:'MCX_FO',underlyingSymbol:symbol,asOf:at(oct+time+'+05:30')});
assert.equal(commodityGroup('GOLDM'),'NON_AGRI');
assert.equal(commodityGroup('CRUDEOILM'),'NON_AGRI');
assert.equal(commodityGroup('SILVERMIC'),'NON_AGRI');
assert.equal(commodityGroup('COPPER'),'NON_AGRI');
assert.equal(commodityGroup('COTTON'),'SELECT_AGRI');
assert.equal(commodityGroup('MENTHAOIL'),'OTHER_AGRI');
assert.equal(commodityGroup('UNRECOGNIZED_COMMODITY'),'UNKNOWN');
assert.equal(session('GOLD','09:10:00').open,true);
assert.equal(session('GOLD','21:30:00').open,true);
assert.equal(session('GOLD','23:20:00').open,false,'Risk cutoff before MCX close');
assert.equal(session('GOLD','23:30:00').clockOpen,false);
assert.equal(session('MENTHAOIL','16:40:00').open,true);
assert.equal(session('MENTHAOIL','16:50:00').open,false);
assert.equal(session('MENTHAOIL','17:00:00').clockOpen,false);
assert.equal(session('COTTON','20:40:00').open,true);
assert.equal(session('COTTON','20:55:00').open,false);
assert.equal(session('UNRECOGNIZED_COMMODITY','14:00:00').open,false,'Unknown agricultural group blocks');
assert.equal(marketClockState({segment:'MCX_FO',underlyingSymbol:'GOLD',asOf:at('2026-11-03T23:35:00+05:30')}).open,true,'Post DST 23:55 session');
assert.equal(marketClockState({segment:'MCX_FO',underlyingSymbol:'GOLD',asOf:at('2028-06-01T14:00:00+05:30')}).open,false,'Unverified DST year fails closed');
assert.equal(marketClockState({segment:'MCX_FO',underlyingSymbol:'GOLD',asOf:at('2026-10-10T13:00:00+05:30')}).open,false,'Weekend closed');
const future={segment:'MCX_FO',instrumentType:'FUT',underlyingSymbol:'GOLD',tradingSymbol:'GOLD FUT 05 NOV 26',
 expiry:'2026-11-05',lotSize:100,tickSize:1,qtyMultiplier:1};
const option={...future,instrumentType:'CE',strike:100000};
const futureMeta=classifyIntradayInstrument(future);
const optionMeta=classifyIntradayInstrument(option);
assert.equal(futureMeta.kind,'COMMODITY_FUTURE');
assert.equal(optionMeta.kind,'COMMODITY_CALL_OPTION');
assert.equal(classifyIntradayInstrument({...option,instrumentType:'PE'}).kind,'COMMODITY_PUT_OPTION');
assert.equal(futureMeta.valid,true);
assert.equal(optionMeta.valid,true);
assert.equal(classifyIntradayInstrument({...future,tickSize:null}).valid,false);
assert.equal(classifyIntradayInstrument({...option,strike:0}).valid,false);
assert.equal(classifyIntradayInstrument({...future,underlyingSymbol:''}).valid,false);
const now=at(oct+'14:05:00+05:30');
const mcx=marketClockState({segment:'MCX_FO',underlyingSymbol:'GOLD',asOf:now});
const first=at(oct+'09:00:00+05:30');
const candles=Array.from({length:62},(_,i)=>({datetime:new Date(first+i*5*60000).toISOString(),
 open:100+i*0.1,high:101+i*0.1,low:99+i*0.1,close:100.5+i*0.1,volume:1000}));
const research=analyzeIntradayCandles(candles,{asOf:now,intervalMinutes:5,session:mcx});
assert.equal(research.valid,true);
assert.equal(research.session.exchange,'MCX');
assert.ok(research.completedBars>=35);
const key='MCX_FO|12345';
const quote=extractUpstoxLiveQuoteEvidence({instrumentKey:key,bid:50000,ask:50001,lastPrice:50000.5,timestamp:now,lastTradeTime:now,openInterest:1000,tradedVolume:12000},key,now);
assert.equal(quote.valid,true);
assert.ok(quote.spreadPercent<0.5);
const staleTrade=extractUpstoxLiveQuoteEvidence({instrumentKey:key,bid:50000,ask:50001,lastPrice:50000.5,
 timestamp:now,lastTradeTime:now-5*60000,openInterest:1000},key,now);
assert.equal(staleTrade.valid,false,'A fresh response must not conceal an old last trade');
assert.ok(staleTrade.reasons.includes('LAST_TRADE_STALE_OR_UNDATED'));
assert.equal(extractUpstoxLiveQuoteEvidence({instrumentKey:key,bid:50000,ask:50001,lastPrice:50000.5,
 timestamp:now,openInterest:1000},key,now).valid,false,'Missing actual last trade fails closed');
assert.equal(extractUpstoxLiveQuoteEvidence({instrumentKey:key,bid:50000,ask:50001,lastPrice:50000,timestamp:now-300000,lastTradeTime:now},key,now).valid,false);
assert.equal(extractUpstoxLiveQuoteEvidence({instrumentKey:'MCX_FO|999',bid:50000,ask:50001,lastPrice:50000,timestamp:now,lastTradeTime:now},key,now).valid,false);
const risk=assessIntradayInstrumentRisk({instrument:future,quote,research,asOf:now,
 openInterest:quote.openInterest,marginVerified:true,deliveryRiskVerified:true,session:mcx});
assert.equal(risk.valid,false,'Exchange holiday and broker cutoff validation is not yet integrated');
assert.ok(risk.reasons.includes('MCX_HOLIDAY_CALENDAR_NOT_VERIFIED'));
assert.ok(risk.reasons.includes('MCX_BROKER_SQUARE_OFF_NOT_VERIFIED'));
const weak=assessIntradayInstrumentRisk({instrument:future,quote,research,asOf:now,session:mcx});
assert.ok(weak.reasons.includes('FUTURES_MARGIN_NOT_VERIFIED'));
assert.ok(weak.reasons.includes('MCX_DELIVERY_AND_TENDER_PERIOD_NOT_VERIFIED'));
assert.ok(weak.reasons.includes('OPEN_INTEREST_NOT_VERIFIED'));
assert.ok(assessIntradayInstrumentRisk({instrument:{...future,qtyMultiplier:null},quote,research,asOf:now,session:mcx}).reasons.includes('MCX_QTY_MULTIPLIER_NOT_VERIFIED'));
assert.ok(assessIntradayInstrumentRisk({instrument:option,quote,research,asOf:now,session:mcx}).reasons.includes('OPTION_GREEKS_NOT_VERIFIED'));
const expiry=assessIntradayInstrumentRisk({instrument:{...future,expiry:'2026-10-08'},quote,research,asOf:now,session:mcx});
assert.ok(expiry.reasons.includes('MCX_EXPIRY_DAY_DELIVERY_RISK'));
const result=evaluateIntradayRecommendation({instrument:future,candles,research,risk,sessionOpen:mcx.open,asOf:now,spreadPercent:quote.spreadPercent});
assert.equal(result.recommendation,'WAIT');
assert.equal(result.confidence,null);
assert.equal(result.estimatedSuccessProbability,null);
assert.equal(result.orderSubmissionAllowed,false);
assert.equal(INTRADAY_SAFETY.PAPER_ONLY,true);
assert.equal(INTRADAY_SAFETY.REAL_ORDER_PLACED,false);
assert.equal(INTRADAY_SAFETY.PRODUCTION_REAL_TRADING_ENABLED,false);
console.log('MCX intraday session, commodity futures/options risk and live-quote fail-closed tests PASSED');
