// Guard against accidentally restoring the legacy advanced-search interface.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=path=>readFileSync(new URL(path,import.meta.url),'utf8');
const entry=read('./intradayRecommendationsUI.js');
const form=read('./autoOptionResearchUI.js');
const demo=read('./indexDemoSessionUI.js');
const backend=read('../server/upstoxOAuthCallbackServer.js');
const signal=read('./services/autoOptionResearchEngine.js');
assert.match(entry,/mountAndroidBottomNavigation\(\)/,
 'Public web app must use the four-tab, read-only recommendation card');
assert.doesNotMatch(entry,/mountAutoOptionResearch\(\)|mountIndexDemoJournal\(\)/,
 'Detailed engineering panels are not mounted in the public web app');
assert.doesNotMatch(entry,/mountIntradayRecommendations\(\)/);
assert.doesNotMatch(entry,/ir-kind|ir-find|ir-contract|ir-interval/);
assert.match(form,/id="ir-auto-type"/);
assert.match(form,/id="ir-auto-symbol"/);
assert.match(form,/id="ir-auto-analyze"/);
assert.match(form,/id="ir-color-option-card"/);
for(const id of ['ir-card-contract','ir-card-buy','ir-card-stop','ir-card-t1','ir-card-t2','ir-card-t3','ir-card-lots'])
 assert.ok(form.includes('id="'+id+'"'),'Missing colored card field '+id);
assert.match(form,/renderColorOptionCard/);
assert.match(form,/renderColorOptionCard\(null,null,early.direction\)/);
assert.match(form,/Target 3 \(3R\)/);
assert.match(form,/Approved: 0/);
assert.match(form,/id="ir-opening-evidence"/);
assert.match(form,/id="ir-no-signal-panel"/);
assert.match(form,/describeIndexOptionGates/);
assert.match(form,/showIndexGates/);
assert.match(form,/Why no CALL \/ PUT option/);
assert.match(form,/deriveOpeningRangeBias/);
assert.match(form,/Completed 5m breakout/);
assert.match(form,/openingRangeProgress/);
assert.match(form,/WAIT — Collecting the 09:15–09:30 opening range/);
assert.match(demo,/09:15–09:30/);
assert.match(demo,/minutes<570/);
assert.match(demo,/minutes===570/);
assert.doesNotMatch(demo,/09:20–15:20 IST checks/);
assert.match(form,/id="ir-freeze-state"/);
assert.match(form,/frozenResearchWindow/);
assert.match(form,/setInterval\(maybeRefreshFiveMinuteResearch,MARKET_QUOTE_POLL_MS\)/);
assert.match(form,/capturedSlot===window.slot/);
assert.match(form,/WAIT — EXPIRED/);
assert.doesNotMatch(form,/now-lastResearchAt>120000/);
assert.match(form,/Connect Upstox/);
assert.match(form,/REAL ORDERS BLOCKED/);
assert.match(form,/MCX Commodity Options/);
assert.match(form,/NIFTY \/ BANKNIFTY \/ SENSEX/);
assert.doesNotMatch(form,/ir-auto-advanced|Show advanced research controls|oldPanels/);
assert.match(demo,/Arm today.s paper demo/);
assert.match(demo,/Export CSV/);
assert.match(backend,/\/api\/upstox\/derivative-search/);
assert.match(backend,/\/api\/upstox\/option-contracts/);
assert.match(signal,/orderSubmissionAllowed:false/);
console.log('SIMPLE WEB RECOMMENDATION UI QUALIFICATION PASSED: public four-tab card, legacy research source retained but hidden, broker lookups and paper-only safety retained');
