import { createPaperTradingRuntime,assertPaperRuntimeSafe } from './paperTradingRuntimeEngine.js';
import { buildPaperCandidateFromDecision,evaluatePaperExit } from './services/paperDecisionBridge.js';
const decision={symbol:'TEST',recommendation:'BUY',paperEligible:true,riskGatesPassed:true,entryZone:{low:99,high:100},stopLoss:95,targets:[110,115],riskRewardRatio:2,opportunityScore:85,paperOnly:true,realOrderPlaced:false};
let failed=0;const check=(n,p)=>{console.log((p?'PASS ':'FAIL ')+n);if(!p)failed++;};
const rejected=buildPaperCandidateFromDecision({...decision,paperEligible:false},1);
check('WAIT/ineligible cannot stage',rejected.valid===false);
const candidate=buildPaperCandidateFromDecision(decision,2);
check('qualified BUY creates paper candidate',candidate.valid&&candidate.paperOnly&&!candidate.realOrderPlaced);
const rt=createPaperTradingRuntime({initialCapital:100000});
const staged=rt.stageCandidate(candidate);check('candidate stages',staged.status==='PAPER_QUEUED');
const filled=rt.fillOrder(staged.id,100);check('paper fill creates position',filled.position?.status==='OPEN');
const marked=rt.mark('TEST',105);check('mark updates unrealized PnL',marked.unrealizedPnL>0);
const hold=evaluatePaperExit(filled.position,candidate,105);check('between stop and target holds',hold.action==='HOLD');
const target=evaluatePaperExit(filled.position,candidate,110);check('target triggers simulated close',target.action==='CLOSE'&&target.reason==='TARGET_HIT');
const closed=rt.close('TEST',110);check('close realizes PnL',closed.status==='CLOSED'&&closed.realizedPnL>0);
const state=rt.getState();check('journal receives closed trade',state.journal.length===1&&state.journal[0].result==='WIN');
check('runtime remains paper safe',assertPaperRuntimeSafe(rt));
const rt2=createPaperTradingRuntime({initialCapital:100000});const s2=rt2.stageCandidate(candidate);const f2=rt2.fillOrder(s2.id,100);const stop=evaluatePaperExit(f2.position,candidate,95);check('stop triggers simulated close',stop.action==='CLOSE'&&stop.reason==='STOP_LOSS_HIT');rt2.close('TEST',95);check('stop loss journaled',rt2.getState().journal[0].result==='LOSS');
console.log('STAGE_D_PAPER_LIFECYCLE_QUALIFICATION='+(failed?'FAILED':'PASSED'));console.log('PAPER_ONLY=true');console.log('REAL_ORDER_PLACED=false');process.exit(failed?1:0);
