import { createStage3ExtendedRealTimePaperObservationEngine, STAGE3_ACTIVITIES } from './stage3ExtendedRealTimePaperObservationEngine.js';
export function runStage3ExtendedRealTimePaperObservationValidation(){
 const e=createStage3ExtendedRealTimePaperObservationEngine(),results=[];const check=(name,p)=>{p=!!p;results.push({name,passed:p});console.log(`${p?'✅':'❌'} ${name}`);};const s=e.getSafety();
 check('10 Stage 3 activities are registered',STAGE3_ACTIVITIES.length===10);check('Stage IDs are contiguous 86–95',STAGE3_ACTIVITIES.every((x,i)=>x.id===86+i));check('Paper-only safety is enabled',s.PAPER_ONLY===true);check('No real order is placed',s.REAL_ORDER_PLACED===false);check('Production real trading is disabled',s.PRODUCTION_REAL_TRADING_ENABLED===false);
 check('Extended observation session starts',e.start({symbol:'NIFTY',session:'STAGE3-VALIDATION'}).started===true);const t=Date.now();check('Fresh tick is accepted',e.observeTick({symbol:'NIFTY',price:25000,timestamp:t,volume:1000}).accepted===true);check('Duplicate tick is rejected',e.observeTick({symbol:'NIFTY',price:25000,timestamp:t,volume:1000}).reason==='DUPLICATE');check('Out-of-order tick is rejected',e.observeTick({symbol:'NIFTY',price:24999,timestamp:t-1,volume:1000}).reason==='OUT_OF_ORDER');check('Signal observation is tracked',e.observeSignal({action:'BUY',score:88}).accepted===true);
 const en=e.paperEntry({id:'S3-P1',symbol:'NIFTY',side:'BUY',quantity:1,price:25000});check('Paper entry is simulated',en.executed===true&&en.realOrderPlaced===false);const ex=e.paperExit('S3-P1',25100);check('Paper outcome is recorded',ex.closed===true&&ex.trade.pnl===100&&ex.realOrderPlaced===false);check('Heartbeat is observable',e.heartbeat().healthy===true);check('Source interruption is fail-safe',e.interrupt('VALIDATION').safe===true);check('Recovery remains gated',e.recover().gatedUntilFreshTick===true);check('Recovered source accepts fresh tick',e.observeTick({symbol:'NIFTY',price:25100,timestamp:Date.now(),volume:1000}).accepted===true);
 const cp=e.createCheckpoint();check('Observation checkpoint is created',cp.created===true&&cp.paperOnly===true);const snap=e.snapshot();check('Observation evidence is populated',snap.evidence.length>=5);check('Observation metrics are exposed',snap.metrics.acceptedTicks>=2&&snap.metrics.rejectedTicks>=2&&snap.metrics.signalCount>=1&&snap.metrics.outcomeCount>=1);check('Final snapshot remains paper-only',snap.safety.PAPER_ONLY===true&&snap.safety.REAL_ORDER_PLACED===false&&snap.safety.PRODUCTION_REAL_TRADING_ENABLED===false);check('Session closes cleanly',e.stop().stopped===true);
 const passed=results.filter(x=>x.passed).length;const r={passed,failed:results.length-passed,allAssertionsPassed:results.every(x=>x.passed),suiteStatus:results.every(x=>x.passed)?'PASSED':'FAILED',paperOnly:true,realOrderPlaced:false,productionRealTradingEnabled:false,results,snapshot:snap};console.table(results);console.log(`STAGE 3 EXTENDED REAL-TIME PAPER OBSERVATION: ${r.suiteStatus}`);return r;
}
